# Generated by Django 4.2.1 on 2023-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('salary', models.BigIntegerField()),
                ('contact', models.BigIntegerField()),
            ],
            options={
                'db_table': 'hiii',
            },
        ),
    ]
