# Generated by Django 4.2.1 on 2023-07-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp',
            new_name='emp1',
        ),
        migrations.AlterModelTable(
            name='emp1',
            table='hiii1',
        ),
    ]
