# Generated by Django 4.2.1 on 2023-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abapp', '0002_rename_emp_emp1_alter_emp1_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp2',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
